/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 10
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_newline = 1,
  anon_sym_system_COLON = 2,
  anon_sym_s_COLON = 3,
  anon_sym_user_COLON = 4,
  anon_sym_u_COLON = 5,
  anon_sym_assistant_COLON = 6,
  anon_sym_a_COLON = 7,
  anon_sym_tool_call_COLON = 8,
  anon_sym_tc_COLON = 9,
  anon_sym_tool_result_COLON = 10,
  anon_sym_tr_COLON = 11,
  anon_sym_comment_COLON = 12,
  anon_sym_c_COLON = 13,
  anon_sym_error_COLON = 14,
  anon_sym_err_COLON = 15,
  sym_text = 16,
  sym_variable = 17,
  sym_escaped_variable = 18,
  sym_source_file = 19,
  sym_chat_entry = 20,
  sym_role = 21,
  sym_content = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_content_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_newline] = "newline",
  [anon_sym_system_COLON] = "system:",
  [anon_sym_s_COLON] = "s:",
  [anon_sym_user_COLON] = "user:",
  [anon_sym_u_COLON] = "u:",
  [anon_sym_assistant_COLON] = "assistant:",
  [anon_sym_a_COLON] = "a:",
  [anon_sym_tool_call_COLON] = "tool_call:",
  [anon_sym_tc_COLON] = "tc:",
  [anon_sym_tool_result_COLON] = "tool_result:",
  [anon_sym_tr_COLON] = "tr:",
  [anon_sym_comment_COLON] = "comment:",
  [anon_sym_c_COLON] = "c:",
  [anon_sym_error_COLON] = "error:",
  [anon_sym_err_COLON] = "err:",
  [sym_text] = "text",
  [sym_variable] = "variable",
  [sym_escaped_variable] = "escaped_variable",
  [sym_source_file] = "source_file",
  [sym_chat_entry] = "chat_entry",
  [sym_role] = "role",
  [sym_content] = "content",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_newline] = sym_newline,
  [anon_sym_system_COLON] = anon_sym_system_COLON,
  [anon_sym_s_COLON] = anon_sym_s_COLON,
  [anon_sym_user_COLON] = anon_sym_user_COLON,
  [anon_sym_u_COLON] = anon_sym_u_COLON,
  [anon_sym_assistant_COLON] = anon_sym_assistant_COLON,
  [anon_sym_a_COLON] = anon_sym_a_COLON,
  [anon_sym_tool_call_COLON] = anon_sym_tool_call_COLON,
  [anon_sym_tc_COLON] = anon_sym_tc_COLON,
  [anon_sym_tool_result_COLON] = anon_sym_tool_result_COLON,
  [anon_sym_tr_COLON] = anon_sym_tr_COLON,
  [anon_sym_comment_COLON] = anon_sym_comment_COLON,
  [anon_sym_c_COLON] = anon_sym_c_COLON,
  [anon_sym_error_COLON] = anon_sym_error_COLON,
  [anon_sym_err_COLON] = anon_sym_err_COLON,
  [sym_text] = sym_text,
  [sym_variable] = sym_variable,
  [sym_escaped_variable] = sym_escaped_variable,
  [sym_source_file] = sym_source_file,
  [sym_chat_entry] = sym_chat_entry,
  [sym_role] = sym_role,
  [sym_content] = sym_content,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_system_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_user_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assistant_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_a_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tool_call_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tc_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tool_result_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tr_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_comment_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_c_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_error_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_err_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_chat_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_role] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        '\n', 3,
        '@', 71,
        'a', 18,
        'c', 19,
        'e', 53,
        's', 20,
        't', 35,
        'u', 21,
      );
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 1:
      if (lookahead == '}') ADVANCE(67);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_system_COLON);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_s_COLON);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_user_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_u_COLON);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_assistant_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_a_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_tool_call_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_tc_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_tool_result_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_tr_COLON);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_comment_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_c_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_error_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_err_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == 's') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == 'y') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(7);
      if (lookahead == 's') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '_') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(51);
      if (lookahead == 'r') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(33);
      if (lookahead == 'r') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'm') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'm') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'm') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'o') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_variable);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '{') ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '}') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_escaped_variable);
      if (lookahead == '@') ADVANCE(68);
      if (lookahead == '{') ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(70);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [anon_sym_system_COLON] = ACTIONS(1),
    [anon_sym_s_COLON] = ACTIONS(1),
    [anon_sym_user_COLON] = ACTIONS(1),
    [anon_sym_u_COLON] = ACTIONS(1),
    [anon_sym_assistant_COLON] = ACTIONS(1),
    [anon_sym_a_COLON] = ACTIONS(1),
    [anon_sym_tool_call_COLON] = ACTIONS(1),
    [anon_sym_tc_COLON] = ACTIONS(1),
    [anon_sym_tool_result_COLON] = ACTIONS(1),
    [anon_sym_tr_COLON] = ACTIONS(1),
    [anon_sym_comment_COLON] = ACTIONS(1),
    [anon_sym_c_COLON] = ACTIONS(1),
    [anon_sym_error_COLON] = ACTIONS(1),
    [anon_sym_err_COLON] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_escaped_variable] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(9),
    [sym_chat_entry] = STATE(6),
    [sym_role] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_system_COLON] = ACTIONS(5),
    [anon_sym_s_COLON] = ACTIONS(5),
    [anon_sym_user_COLON] = ACTIONS(5),
    [anon_sym_u_COLON] = ACTIONS(5),
    [anon_sym_assistant_COLON] = ACTIONS(5),
    [anon_sym_a_COLON] = ACTIONS(5),
    [anon_sym_tool_call_COLON] = ACTIONS(5),
    [anon_sym_tc_COLON] = ACTIONS(5),
    [anon_sym_tool_result_COLON] = ACTIONS(5),
    [anon_sym_tr_COLON] = ACTIONS(5),
    [anon_sym_comment_COLON] = ACTIONS(5),
    [anon_sym_c_COLON] = ACTIONS(5),
    [anon_sym_error_COLON] = ACTIONS(5),
    [anon_sym_err_COLON] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_content] = STATE(8),
    [aux_sym_content_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
    [anon_sym_system_COLON] = ACTIONS(7),
    [anon_sym_s_COLON] = ACTIONS(7),
    [anon_sym_user_COLON] = ACTIONS(7),
    [anon_sym_u_COLON] = ACTIONS(7),
    [anon_sym_assistant_COLON] = ACTIONS(7),
    [anon_sym_a_COLON] = ACTIONS(7),
    [anon_sym_tool_call_COLON] = ACTIONS(7),
    [anon_sym_tc_COLON] = ACTIONS(7),
    [anon_sym_tool_result_COLON] = ACTIONS(7),
    [anon_sym_tr_COLON] = ACTIONS(7),
    [anon_sym_comment_COLON] = ACTIONS(7),
    [anon_sym_c_COLON] = ACTIONS(7),
    [anon_sym_error_COLON] = ACTIONS(7),
    [anon_sym_err_COLON] = ACTIONS(7),
    [sym_text] = ACTIONS(11),
    [sym_variable] = ACTIONS(9),
    [sym_escaped_variable] = ACTIONS(11),
  },
  [STATE(3)] = {
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_newline] = ACTIONS(15),
    [anon_sym_system_COLON] = ACTIONS(13),
    [anon_sym_s_COLON] = ACTIONS(13),
    [anon_sym_user_COLON] = ACTIONS(13),
    [anon_sym_u_COLON] = ACTIONS(13),
    [anon_sym_assistant_COLON] = ACTIONS(13),
    [anon_sym_a_COLON] = ACTIONS(13),
    [anon_sym_tool_call_COLON] = ACTIONS(13),
    [anon_sym_tc_COLON] = ACTIONS(13),
    [anon_sym_tool_result_COLON] = ACTIONS(13),
    [anon_sym_tr_COLON] = ACTIONS(13),
    [anon_sym_comment_COLON] = ACTIONS(13),
    [anon_sym_c_COLON] = ACTIONS(13),
    [anon_sym_error_COLON] = ACTIONS(13),
    [anon_sym_err_COLON] = ACTIONS(13),
    [sym_text] = ACTIONS(17),
    [sym_variable] = ACTIONS(15),
    [sym_escaped_variable] = ACTIONS(17),
  },
  [STATE(4)] = {
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_newline] = ACTIONS(21),
    [anon_sym_system_COLON] = ACTIONS(19),
    [anon_sym_s_COLON] = ACTIONS(19),
    [anon_sym_user_COLON] = ACTIONS(19),
    [anon_sym_u_COLON] = ACTIONS(19),
    [anon_sym_assistant_COLON] = ACTIONS(19),
    [anon_sym_a_COLON] = ACTIONS(19),
    [anon_sym_tool_call_COLON] = ACTIONS(19),
    [anon_sym_tc_COLON] = ACTIONS(19),
    [anon_sym_tool_result_COLON] = ACTIONS(19),
    [anon_sym_tr_COLON] = ACTIONS(19),
    [anon_sym_comment_COLON] = ACTIONS(19),
    [anon_sym_c_COLON] = ACTIONS(19),
    [anon_sym_error_COLON] = ACTIONS(19),
    [anon_sym_err_COLON] = ACTIONS(19),
    [sym_text] = ACTIONS(24),
    [sym_variable] = ACTIONS(21),
    [sym_escaped_variable] = ACTIONS(24),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_newline] = ACTIONS(27),
    [anon_sym_system_COLON] = ACTIONS(27),
    [anon_sym_s_COLON] = ACTIONS(27),
    [anon_sym_user_COLON] = ACTIONS(27),
    [anon_sym_u_COLON] = ACTIONS(27),
    [anon_sym_assistant_COLON] = ACTIONS(27),
    [anon_sym_a_COLON] = ACTIONS(27),
    [anon_sym_tool_call_COLON] = ACTIONS(27),
    [anon_sym_tc_COLON] = ACTIONS(27),
    [anon_sym_tool_result_COLON] = ACTIONS(27),
    [anon_sym_tr_COLON] = ACTIONS(27),
    [anon_sym_comment_COLON] = ACTIONS(27),
    [anon_sym_c_COLON] = ACTIONS(27),
    [anon_sym_error_COLON] = ACTIONS(27),
    [anon_sym_err_COLON] = ACTIONS(27),
    [sym_text] = ACTIONS(29),
    [sym_variable] = ACTIONS(27),
    [sym_escaped_variable] = ACTIONS(29),
  },
  [STATE(6)] = {
    [sym_chat_entry] = STATE(7),
    [sym_role] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_system_COLON] = ACTIONS(5),
    [anon_sym_s_COLON] = ACTIONS(5),
    [anon_sym_user_COLON] = ACTIONS(5),
    [anon_sym_u_COLON] = ACTIONS(5),
    [anon_sym_assistant_COLON] = ACTIONS(5),
    [anon_sym_a_COLON] = ACTIONS(5),
    [anon_sym_tool_call_COLON] = ACTIONS(5),
    [anon_sym_tc_COLON] = ACTIONS(5),
    [anon_sym_tool_result_COLON] = ACTIONS(5),
    [anon_sym_tr_COLON] = ACTIONS(5),
    [anon_sym_comment_COLON] = ACTIONS(5),
    [anon_sym_c_COLON] = ACTIONS(5),
    [anon_sym_error_COLON] = ACTIONS(5),
    [anon_sym_err_COLON] = ACTIONS(5),
  },
  [STATE(7)] = {
    [sym_chat_entry] = STATE(7),
    [sym_role] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_system_COLON] = ACTIONS(35),
    [anon_sym_s_COLON] = ACTIONS(35),
    [anon_sym_user_COLON] = ACTIONS(35),
    [anon_sym_u_COLON] = ACTIONS(35),
    [anon_sym_assistant_COLON] = ACTIONS(35),
    [anon_sym_a_COLON] = ACTIONS(35),
    [anon_sym_tool_call_COLON] = ACTIONS(35),
    [anon_sym_tc_COLON] = ACTIONS(35),
    [anon_sym_tool_result_COLON] = ACTIONS(35),
    [anon_sym_tr_COLON] = ACTIONS(35),
    [anon_sym_comment_COLON] = ACTIONS(35),
    [anon_sym_c_COLON] = ACTIONS(35),
    [anon_sym_error_COLON] = ACTIONS(35),
    [anon_sym_err_COLON] = ACTIONS(35),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(38),
    [anon_sym_system_COLON] = ACTIONS(38),
    [anon_sym_s_COLON] = ACTIONS(38),
    [anon_sym_user_COLON] = ACTIONS(38),
    [anon_sym_u_COLON] = ACTIONS(38),
    [anon_sym_assistant_COLON] = ACTIONS(38),
    [anon_sym_a_COLON] = ACTIONS(38),
    [anon_sym_tool_call_COLON] = ACTIONS(38),
    [anon_sym_tc_COLON] = ACTIONS(38),
    [anon_sym_tool_result_COLON] = ACTIONS(38),
    [anon_sym_tr_COLON] = ACTIONS(38),
    [anon_sym_comment_COLON] = ACTIONS(38),
    [anon_sym_c_COLON] = ACTIONS(38),
    [anon_sym_error_COLON] = ACTIONS(38),
    [anon_sym_err_COLON] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chat_entry, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_role, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chat_entry, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_chat(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "chat",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
